services:
  # Frontend (React App)
  - type: web
    name: bitealert-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://bitealert-backend.onrender.com
      - key: NODE_ENV
        value: production

  # Backend (Node.js API)
  - type: web
    name: bitealert-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: bitealert-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false

databases:
  - name: bitealert-db
    plan: free
    databaseName: bitealert
    user: bitealert_user
